const { ProductModel } = require("../models");

const product = async () => {
    try {
        const insertRecords = [
            { "title": "Neuro Seliron 300", "slug": "neuro-seliron-300" },
            { "title": "Asthalin Inhaler", "slug": "asthalin-inhaler-2" },
            { "title": "Tri-Luma Cream", "slug": "tri-luma-cream" },
            { "title": "Zopifresh 7.5 mg", "slug": "zopifresh-7-5-mg" },
            { "title": "Modalert 200", "slug": "modalert-200" },
            { "title": "Artvigil 150 mg", "slug": "artvigil-150-mg" },
            { "title": "Waklert 150", "slug": "waklert-150" },
            { "title": "Asthalin 4 Mg", "slug": "asthalin-4-mg" },
            { "title": "zinconia 50MG (Zinc)", "slug": "zinconia-50mg-zinc" },
            { "title": "Moluzen Molnupiravir 200", "slug": "moluzen-molnupiravir-200-2" },
            { "title": "Nirmatrelvir 150 And Ritonavir 100", "slug": "nirmatrelvir-150-and-ritonavir-100" },
            { "title": "Recalmin D3 (Vitamin D)", "slug": "recalmin-d3-vitamin-d" },
            { "title": "Amdatime 100MG (Amantadin)", "slug": "amdatime-100mg-amantadin" },
            { "title": "Ribasure 200 (Ribavirin)", "slug": "ribasure-200-ribavirin" },
            { "title": "Niclosamide 500 mg", "slug": "niclosamide-500-mg" },
            { "title": "ZBD Plus 12 mg (Albendazole &amp; Ivermectin)", "slug": "zbd-plus-12-mg-albendazole-ivermectin" },
            { "title": "Itraconazole Capsules 100 mg", "slug": "itraconazole-capsules-100-mg" },
            { "title": "Ashwagandha", "slug": "ashwagandha" },
            { "title": "Clindamycin 300 Mg", "slug": "clindamycin-300-mg" },
            { "title": "Betnovate-N Cream", "slug": "betnovate-n-cream" },
            { "title": "Betnovate Cream (Betamethasone)", "slug": "betnovate-cream-betamethasone" },
            { "title": "Betnovate M Cream (Betamethasone\/Miconazole)", "slug": "betnovate-m-cream-betamethasone-miconazole" },
            { "title": "Shilajit Gold resin 100% Pure", "slug": "shilajit-gold-resin-100-pure" },
            { "title": "Clenbuterol 60 MCG", "slug": "clenbuterol-60-mcg" },
            { "title": "Mebendazole 500 mg", "slug": "mebendazole-500-mg" },
            { "title": "Albendazole 400 mg", "slug": "albendazole-400-mg" },
            { "title": "Kaymedorol 16 mg (Methylprednisolone)", "slug": "kaymedorol-16-mg-methylprednisolone" },
            { "title": "Kaymedorol 4 mg (Methylprednisolone)", "slug": "kaymedorol-4-mg-methylprednisolone" },
            { "title": "Kaymedorol 8 mg (Methylprednisolone)", "slug": "kaymedorol-8-mg-methylprednisolone" },
            { "title": "Celkeran 5 mg (Chlorambucil)", "slug": "celkeran-5-mg-chlorambucil" },
            { "title": "Celkeran 2 mg (Chlorambucil)", "slug": "celkeran-2-mg-chlorambucil" },
            { "title": "Tenofovir Alafenamide Taficita 200Mg \/25Mg Tablets", "slug": "tenofovir-alafenamide-taficita-200mg-25mg-tablets" },
            { "title": "Limcee 500 mg (Vitamin C)", "slug": "limcee-500-mg-vitamin-c" },
            { "title": "Afatinib 20 mg", "slug": "afatinib-20-mg" },
            { "title": "Ceritinib 150 mg", "slug": "ceritinib-150-mg" },
            { "title": "Afatinib 30 mg", "slug": "afatinib-30-mg" },
            { "title": "Afatinib 40 mg", "slug": "afatinib-40-mg" },
            { "title": "Paxlovid", "slug": "paxlovid" },
            { "title": "Flutamide 250 mg", "slug": "flutamide-250-mg" },
            { "title": "Leuprolide Acetate 1 mg", "slug": "leuprolide-acetate-1-mg" },
            { "title": "Nasoclear Salina Nasal Spray", "slug": "nasoclear-salina-nasal-spray" },
            { "title": "Budesonide Inhaler 100", "slug": "budesonide-inhaler-100" },
            { "title": "Levolin synchro breathe Inhaler", "slug": "levolin-synchro-breathe-inhaler" },
            { "title": "Flohale 0.5 mg Respules", "slug": "flohale-0-5-mg-respules-2" },
            { "title": "Flohale 2 mg Respules", "slug": "flohale-2-mg-respules-2" },
            { "title": "Budesonide 400 Rotacaps", "slug": "budesonide-400-rotacaps" },
            { "title": "Budesonide AQ Nasal Spray", "slug": "budesonide-aq-nasal-spray" },
            { "title": "Regorafenib 40 mg", "slug": "regorafenib-40-mg" },
            { "title": "Budesonide 200 Inhaler", "slug": "budesonide-200-inhaler" },
            { "title": "Budesonide 1 Respules", "slug": "budesonide-1-respules" },
            { "title": "Letrozole 5 mg", "slug": "letrozole-5-mg" },
            { "title": "Imiquimod Sachet", "slug": "imiquimod-sachet" },
            { "title": "Enzalutamide 40 mg", "slug": "enzalutamide-40-mg" },
            { "title": "Augmentin 1g", "slug": "augmentin-1g" },
            { "title": "Bactrim DS", "slug": "bactrim-ds" },
            { "title": "Seroflo Ciphaler 500 mcg", "slug": "seroflo-ciphaler-500-mcg" },
            { "title": "Flohale 0.5 mg Respules", "slug": "flohale-0-5-mg-respules" },
            { "title": "Flohale 2 mg Respules", "slug": "flohale-2-mg-respules" },
            { "title": "Carisoprodol 750 mg (Pain O Soma)", "slug": "carisoprodol-750-mg-pain-o-soma" },
            { "title": "Carisoprodol 1000 mg (Pain O Soma)", "slug": "carisoprodol-1000-mg-pain-o-soma" },
            { "title": "Testosterone Gel 5GM (Cernos)", "slug": "testosterone-gel-5gm-cernos" },
            { "title": "Letrozole Tablets USP 2.5 mg", "slug": "letrozole-tablets-usp-2-5-mg" },
            { "title": "Mebendazole 100 mg", "slug": "mebendazole-100-mg" },
            { "title": "Nitazoxanide 500 Mg", "slug": "nitazoxanide-500-mg" },
            { "title": "Prednisolone dispersible tablets 20 mg (Generic Deltasone)", "slug": "prednisolone-dispersible-tablets-20-mg-generic-deltasone" },
            { "title": "Premarin Vaginal Cream (Conjugated Estrogen)", "slug": "premarin-vaginal-cream-conjugated-estrogen" },
            { "title": "Prednisolone dispersible tablets 10 mg (Generic Deltasone)", "slug": "prednisolone-dispersible-tablets-10-mg-generic-deltasone" },
            { "title": "Prednisolone dispersible tablets 5 mg (Generic Deltasone)", "slug": "prednisolone-dispersible-tablets-5-mg-generic-deltasone" },
            { "title": "Anastrozole 1 mg", "slug": "anastrozole-1-mg" },
            { "title": "Low Dose Naltrexone 1.5 mg", "slug": "low-dose-naltrexone-1-5-mg" },
            { "title": "Low Dose Naltrexone 3 mg", "slug": "low-dose-naltrexone-3-mg" },
            { "title": "Naltrexone 50 mg", "slug": "naltrexone-50-mg" },
            { "title": "Naltrexone &amp; Bupropion", "slug": "naltrexone-bupropion" },
            { "title": "Herbal Sugar Control Pil", "slug": "herbal-sugar-control-pil" },
            { "title": "Hydrocortisone 20 mg", "slug": "hydrocortisone-20-mg" },
            { "title": "Fludrocotisone 100 mcg", "slug": "fludrocotisone-100-mcg" },
            { "title": "Artemisinin 100 mg", "slug": "artemisinin-100-mg" },
            { "title": "Metformin 1000 mg", "slug": "metformin-1000-mg" },
            { "title": "Metformin 850 mg", "slug": "metformin-850-mg" },
            { "title": "Metformin 500 mg", "slug": "metformin-500-mg" },
            { "title": "Budesonide 200 Rotacaps", "slug": "budesonide-200-rotacaps" },
            { "title": "Asthalin Rotacaps 200 mg", "slug": "asthalin-rotacaps-200-mg" },
            { "title": "Asthalin Respules", "slug": "asthalin-respules" },
            { "title": "Asthalin Inhaler", "slug": "asthalin-inhaler" },
            { "title": "Aerocort Rotacaps", "slug": "aerocort-rotacaps" },
            { "title": "Aerocort Inhaler", "slug": "aerocort-inhaler" },
            { "title": "Aerocort Forte Rotacaps", "slug": "aerocort-forte-rotacaps" },
            { "title": "Apixaban tablets 2.5 mg", "slug": "apixaban-tablets-2-5-mg" },
            { "title": "Carisoprodol 350 mg", "slug": "carisoprodol-350-mg" },
            { "title": "Fenbendazole 444 Mg", "slug": "fenbendazole-444-mg" },
            { "title": "Semaglutide - Rybelsus (14mg)", "slug": "semaglutide-rybelsus-14mg" },
            { "title": "Semaglutide - Rybelsus (7mg)", "slug": "semaglutide-rybelsus-7mg" },
            { "title": "Semaglutide - Rybelsus (3mg)", "slug": "semaglutide-rybelsus-3mg" },
            { "title": "Minoxidil 5% solution", "slug": "minoxidil-5-solution" },
            { "title": "Minoxidil 2% solution", "slug": "minoxidil-2-solution" },
            { "title": "Hydroxyurea Capsules IP 500 mg", "slug": "hydroxyurea-capsules-ip-500-mg" },
            { "title": "Valacyclovir Tablets USP 500mg", "slug": "valacyclovir-tablets-usp-500mg" },
            { "title": "Valacyclovir Tablets USP 1000mg", "slug": "valacyclovir-tablets-usp-1000mg" },
            { "title": "Melatonin Mouth Dissolving Tablets", "slug": "melatonin-mouth-dissolving-tablets" },
            { "title": "Tolvaptan tablets 30mg", "slug": "tolvaptan-tablets-30mg" },
            { "title": "Tolvaptan tablets 15mg", "slug": "tolvaptan-tablets-15mg" },
            { "title": "Careprost Eye Drop", "slug": "careprost-eye-drop" },
            { "title": "Isotretinoin 20 mg", "slug": "isotretinoin-20-mg" },
            { "title": "Acne UV sunscreen Gel", "slug": "acne-uv-sunscreen-gel" },
            { "title": "Cosmo Q- Skin brightening Serum", "slug": "cosmo-q-skin-brightening-serum" },
            { "title": "KLMC- vitamin C serum", "slug": "klmc-vitamin-c-serum" },
            { "title": "Gabapentin-800mg", "slug": "gabapentin-800mg" },
            { "title": "Gabapentin-600mg", "slug": "gabapentin-600mg" },
            { "title": "Gabapentin-400mg", "slug": "gabapentin-400mg" },
            { "title": "Gabapentin-300mg", "slug": "gabapentin-300mg" },
            { "title": "Pregabalin-75mg", "slug": "pregabalin-75mg" },
            { "title": "Pregabalin-150mg", "slug": "pregabalin-150mg" },
            { "title": "Pregabalin-300mg", "slug": "pregabalin-300mg" },
            { "title": "Ibrutinib  140Mg Capsules", "slug": "ibrutinib-140mg-capsules" },
            { "title": "Orlistat 60 mg", "slug": "orlistat-60-mg" },
            { "title": "Jardiance 25 Mg", "slug": "jardiance-25-mg" },
            { "title": "Promethazine 10 Mg", "slug": "promethazine-10-mg" },
            { "title": "Finasteride 1 Mg", "slug": "finasteride-1-mg" },
            { "title": "Cabergoline 0.50 Mg", "slug": "cabergoline-0-50-mg" },
            { "title": "Conjugated Estrogen 0.625 mg", "slug": "conjugated-estrogen-0-625-mg" },
            { "title": "Testosterone 40 mg Softgel Capsules", "slug": "testosterone-40-mg-softgel-capsules" },
            { "title": "Promethazine 25 Mg", "slug": "promethazine-25-mg" },
            { "title": "Orlistat 120 mg", "slug": "orlistat-120-mg" },
            { "title": "Clenbuterol 40 Mcg", "slug": "clenbuterol-40-mcg" },
            { "title": "Paxobrook", "slug": "paxobrook" },
            { "title": "Fluvir 75 Mg  (Generic Oseltamivir – Tamiflu)", "slug": "fluvir-75-mg-generic-oseltamivir-tamiflu" },
            { "title": "Fenbendazole 222 Mg", "slug": "fenbendazole-222-mg" },
            { "title": "Naltrexone", "slug": "naltrexone" },
            { "title": "Levocetirizine &amp; Pseudoephedrine", "slug": "levocetirizine-pseudoephedrine" },
            { "title": "Fenbendazole Wormentel 150 mg", "slug": "fenbendazole-wormentel-150-mg" },
            { "title": "Apixaban Tablets 5mg", "slug": "apixaban-tablets-5mg" },
            { "title": "Testacyp-250-Injection", "slug": "testacyp-250-injection" },
            { "title": "Prosoma 350 Mg Tablets", "slug": "prosoma-350-mg-tablets" },
            { "title": "Carisoprodol 500 mg", "slug": "carisoprodol-500-mg" },
            { "title": "Lidocaine &amp; Prilocaine Gel 10 gm", "slug": "lidocaine-prilocaine-gel-10-gm" },
            { "title": "Augmentin 375 mg", "slug": "augmentin-375-mg" },
            { "title": "Ivermectin Cream", "slug": "ivermectin-cream" },
            { "title": "Artecan 120 mg Injection", "slug": "artecan-120-mg-injection" },
            { "title": "Artecan 60 mg Injection", "slug": "artecan-60-mg-injection" },
            { "title": "Norsunate 100 mg", "slug": "norsunate-100-mg" },
            { "title": "Norsunate 50 mg", "slug": "norsunate-50-mg" },
            { "title": "FERAVIR 800 MG", "slug": "feravir-800-mg" },
            { "title": "FERAVIR 400 MG", "slug": "feravir-400-mg" },
            { "title": "FERAVIR 200 MG", "slug": "feravir-200-mg" },
            { "title": "Zycolchin 0.5 mg", "slug": "zycolchin-0-5-mg" },
            { "title": "Flagyl 200 Mg", "slug": "flagyl-200-mg" },
            { "title": "Flagyl 400 Mg", "slug": "flagyl-400-mg" },
            { "title": "Forcan 50 mg", "slug": "forcan-50-mg" },
            { "title": "Forcan 150 mg", "slug": "forcan-150-mg" },
            { "title": "Forcan 200 mg", "slug": "forcan-200-mg" },
            { "title": "Ciplox 250 Mg", "slug": "ciplox-250-mg" },
            { "title": "Ciplox 500 Mg", "slug": "ciplox-500-mg" },
            { "title": "Augmentin 625 mg", "slug": "augmentin-625-mg" },
            { "title": "Azicip 500 Mg", "slug": "azicip-500-mg" },
            { "title": "Azicip 250 Mg", "slug": "azicip-250-mg" },
            { "title": "Doxycycline 100mg", "slug": "doxycycline-100mg" },
            { "title": "Fluvoxin 50 Mg", "slug": "fluvoxin-50-mg" },
            { "title": "Fluvoxin 100 Mg", "slug": "fluvoxin-100-mg" },
            { "title": "Cephadex 250 mg", "slug": "cephadex-250-mg" },
            { "title": "Cephadex 500 mg", "slug": "cephadex-500-mg" },
            { "title": "Azee 500 Mg", "slug": "azee-500-mg" },
            { "title": "Azee 250 Mg", "slug": "azee-250-mg" },
            { "title": "Pirfenex 400 Mg", "slug": "pirfenex-400-mg" },
            { "title": "Pirfenex 200 Mg", "slug": "pirfenex-200-mg" },
            { "title": "Cipmox 500 Mg", "slug": "cipmox-500-mg" },
            { "title": "Cipmox 250 Mg", "slug": "cipmox-250-mg" },
            { "title": "Hqcheal 400 Mg", "slug": "hqcheal-400-mg" },
            { "title": "Hqcheal 200 Mg", "slug": "hqcheal-200-mg" },
            { "title": "HCQS 400 Mg", "slug": "hcqs-400-mg" },
            { "title": "HCQS 200 Mg", "slug": "hcqs-200-mg" },
            { "title": "Ketosteril Tablet", "slug": "ketosteril-tablet" },
            { "title": "Super Kamagra Oral Jelly", "slug": "super-kamagra-oral-jelly" },
            { "title": "Iverjohn 12mg", "slug": "iverjohn-12mg" },
            { "title": "Covimectin 12mg", "slug": "covimectin-12mg" },
            { "title": "Iversun 12mg", "slug": "iversun-12mg" },
            { "title": "Molnucen Molnupiravir 200 Mg", "slug": "molnucen-molnupiravir-200-mg" },
            { "title": "Molnunat Molnupiravir 200", "slug": "molnunat-molnupiravir-200" },
            { "title": "Moluzen Molnupiravir 200", "slug": "moluzen-molnupiravir-200" },
            { "title": "Molnupiravir 200 Mg Capsule", "slug": "molnupiravir-200-mg-capsule" },
            { "title": "Molaz Molnupiravir 200 Mg Capsule", "slug": "molaz-molnupiravir-200-mg-capsule" },
            { "title": "Iverheal 12 mg", "slug": "iverheal-12-mg" },
            { "title": "lverheal 6mg", "slug": "lverheal-6mg" },
            { "title": "Iverheal 3mg", "slug": "iverheal-3mg" },
            { "title": "Movfor Molnupiravir 200 mg", "slug": "movfor-molnupiravir-200-mg" },
            { "title": "Pink Lady 100Mg", "slug": "pink-lady-100mg" },
            { "title": "Vilitra 60mg", "slug": "vilitra-60mg" },
            { "title": "Vilitra 40mg", "slug": "vilitra-40mg" },
            { "title": "Vilitra 20mg", "slug": "vilitra-20mg" },
            { "title": "Vilitra 10mg", "slug": "vilitra-10mg" },
            { "title": "Super Vilitra", "slug": "super-vilitra" },
            { "title": "Vidalista Professional", "slug": "vidalista-professional" },
            { "title": "Vidalista Ct", "slug": "vidalista-ct" },
            { "title": "Vidalista Black 80", "slug": "vidalista-black-80" },
            { "title": "Vidalista 60", "slug": "vidalista-60" },
            { "title": "Vidalista 5", "slug": "vidalista-5" },
            { "title": "Vidalista 40", "slug": "vidalista-40" },
            { "title": "Vidalista 20", "slug": "vidalista-20" },
            { "title": "Vidalista 2.5", "slug": "vidalista-2-5" },
            { "title": "Vidalista 10", "slug": "vidalista-10" },
            { "title": "Tadalista Super Active", "slug": "tadalista-super-active" },
            { "title": "Tadalista Professional 20 Mg", "slug": "tadalista-professional-20-mg" },
            { "title": "Tadalista Ct 20 Mg", "slug": "tadalista-ct-20-mg" },
            { "title": "Tadalista 60", "slug": "tadalista-60" },
            { "title": "Tadalista 40", "slug": "tadalista-40" },
            { "title": "Tadalista 20", "slug": "tadalista-20" },
            { "title": "Tadalista 10", "slug": "tadalista-10" },
            { "title": "Tadacip 20", "slug": "tadacip-20" },
            { "title": "Super P Force Oral Jelly", "slug": "super-p-force-oral-jelly" },
            { "title": "Super P Force", "slug": "super-p-force" },
            { "title": "Super Kamagra", "slug": "super-kamagra" },
            { "title": "Super Fildena", "slug": "super-fildena" },
            { "title": "Suhagra Force", "slug": "suhagra-force" },
            { "title": "Suhagra 50", "slug": "suhagra-50" },
            { "title": "Suhagra 25", "slug": "suhagra-25" },
            { "title": "Suhagra 100", "slug": "suhagra-100" },
            { "title": "Sildigra Super Power", "slug": "sildigra-super-power" },
            { "title": "Sildigra Prof 100Mg", "slug": "sildigra-prof-100mg" },
            { "title": "Sildigra Black Force 200Mg", "slug": "sildigra-black-force-200mg" },
            { "title": "Sildigra 25Mg", "slug": "sildigra-25mg" },
            { "title": "Sildenafil Oral Film 50Mg", "slug": "sildenafil-oral-film-50mg" },
            { "title": "Sildenafil Oral Film 100Mg", "slug": "sildenafil-oral-film-100mg" },
            { "title": "Prejac 60Mg", "slug": "prejac-60mg" },
            { "title": "P Force Fort", "slug": "p-force-fort" },
            { "title": "Maxgun 100Mg", "slug": "maxgun-100mg" },
            { "title": "Kamagra Polo", "slug": "kamagra-polo" },
            { "title": "Kamagra Oral Jelly", "slug": "kamagra-oral-jelly" },
            { "title": "Kamagra 50", "slug": "kamagra-50" },
            { "title": "Kamagra 100", "slug": "kamagra-100" },
            { "title": "Kamagra Full Range", "slug": "kamagra-full-range" },
            { "title": "Kamagra Effervescent", "slug": "kamagra-effervescent" },
            { "title": "Kamagra Chewable", "slug": "kamagra-chewable" },
            { "title": "Fliban", "slug": "fliban" },
            { "title": "Fildena Xxx", "slug": "fildena-xxx" },
            { "title": "Fildena Super Active", "slug": "fildena-super-active" },
            { "title": "Fildena Professional", "slug": "fildena-professional" },
            { "title": "Fildena 200", "slug": "fildena-200" },
            { "title": "Fildena Ct", "slug": "fildena-ct" },
            { "title": "Fildena 50", "slug": "fildena-50" },
            { "title": "Fildena 25", "slug": "fildena-25" },
            { "title": "Fildena 150", "slug": "fildena-150" },
            { "title": "Fildena 120", "slug": "fildena-120" },
            { "title": "Fildena 100", "slug": "fildena-100" },
            { "title": "Extra Super P Force", "slug": "extra-super-p-force" },
            { "title": "Ed Trial Pack", "slug": "ed-trial-pack" },
            { "title": "Ed Duo Pack By Cipla", "slug": "ed-duo-pack-by-cipla" },
            { "title": "Duratia 90", "slug": "duratia-90" },
            { "title": "Duratia 60", "slug": "duratia-60" },
            { "title": "Duratia 30", "slug": "duratia-30" },
            { "title": "Climax Spray", "slug": "climax-spray" },
            { "title": "Cenforce Soft", "slug": "cenforce-soft" },
            { "title": "Cenforce Professional", "slug": "cenforce-professional" },
            { "title": "Cenforce Fm", "slug": "cenforce-fm" },
            { "title": "Cenforce D For Sale", "slug": "cenforce-d-for-sale" },
            { "title": "Cenforce 50", "slug": "cenforce-50" },
            { "title": "Cenforce 25", "slug": "cenforce-25" },
            { "title": "Cenforce 200", "slug": "cenforce-200" },
            { "title": "Cenforce 150", "slug": "cenforce-150" },
            { "title": "Cenforce 120", "slug": "cenforce-120" },
            { "title": "Cenforce 100", "slug": "cenforce-100" },
            { "title": "Avana 50", "slug": "avana-50" },
            { "title": "Avana 200", "slug": "avana-200" },
            { "title": "Avana 100", "slug": "avana-100" },
            { "title": "Ajanta Ed Trial Pack", "slug": "ajanta-ed-trial-pack" }
        ];
        await ProductModel.bulkCreate(insertRecords);
    } catch (error) {
        console.error("product seeder:", error);
    }
};
module.exports = { product };
